### ISSUE TITLE
Alexa can't link to sinric

### ISSUE THREAD

**Issue by jejetica** [kakopappa/sinric#104]
Hello, 

I tried to link to sinric and I get always an error: unable to link skill, try later. I already tried different amazon accounts. maybe someone has an idea what it can to be?

**Comment by kakopappa** [comment]
Yah .. Sorry about this.

 Server SSL certificate has expired I will renew it as soon as I finish
this beer (in few hours)

**Comment by jejetica** [comment]
ah ok, 
I try tomorrow again. Enjoy your beer :)

**Comment by kalingaa** [comment]
if you setup cloudflare in front, the SSL is free from them and the service is also free, plus you don't have to worry about local server cert renewal and it has many other benefits as well.

**Comment by kakopappa** [comment]
Thanks machange . I will take a look this weekend

**Comment by kakopappa** [comment]
![image](https://user-images.githubusercontent.com/7474406/44275289-82d68800-a26e-11e8-8627-d24258b22e9c.png)

done should be fine now. please check and let me know if otherwise

@kalingaa sometimes I sometimes I listen to talk katha. keep up the good work bro.

**Comment by kalingaa** [comment]
@kakopappa honored to have you as a listener buddy! join us for an episode, even via Skype ?

**Comment by kakopappa** [comment]
@kalingaa thanks. i will drop you a message when i am free.

**Comment by jejetica** [comment]
sorry for the late answer, it works. Thank you!

**Comment by RanTalbott** [comment]
I'm still seeing this, but only when Firefox "helpfully" remembers that I had previously logged in via alexa.sinric.com at some point. If I fix the URL and go to just plain sinric.com, I get a different webpage, and the login works correctly. Maybe whatever host is serving https://alexa.sinric.com/login is still using the old certificate?

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server because now closed

**Comment by shikoghaly** [comment]
Hi kakopappa pls renew the server because now closed
